# Generated by Django 4.0.7 on 2024-03-14 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='name',
            new_name='board_name',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='name',
            new_name='task_name',
        ),
        migrations.RenameField(
            model_name='title',
            old_name='name',
            new_name='title_name',
        ),
    ]
