# Generated by Django 3.2.12 on 2024-04-23 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0002_card_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='color',
            field=models.CharField(default='#14BDEB', max_length=7, null=True),
        ),
    ]
