# Generated by Django 4.0.7 on 2024-03-14 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0002_rename_name_board_board_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='board',
            new_name='board_id',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='title_id',
        ),
        migrations.RenameField(
            model_name='title',
            old_name='board',
            new_name='board_id',
        ),
    ]
