# Generated by Django 3.2.12 on 2024-05-08 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20240508_1601'),
        ('kanban', '0003_alter_card_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.team'),
        ),
    ]
