# Generated by Django 3.2.12 on 2024-04-18 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0003_rename_board_task_board_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='board_id',
        ),
    ]
