# Generated by Django 3.2.12 on 2024-05-08 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='directory',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='project_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
