# Generated by Django 5.0.3 on 2024-05-09 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='to_user',
        ),
        migrations.AddField(
            model_name='message',
            name='to_user_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
