# Generated by Django 5.0.3 on 2024-05-09 23:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_remove_message_to_user_message_to_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='to_user_id',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(-1)]),
        ),
    ]
